version: "3"

services:
  redis:
    image: redis:alpine
    command: redis-server --requirepass 123456
    ports:
      - 6379:6379
    environment:
      - REDIS_REPLICATION_MODE=master
  ui:
    image: redislabs/redisinsight:latest
    ports:
      - 8001:8001
