openapi: 3.0.1

tags:
  - name: example
    description: Example API
components:
  securitySchemes:
    x-token:
      type: apiKey
      name: x-token
      in: header
  schemas:
    ApiResponse:
      type: object
      properties:
        data:
          type: object
        status:
          type: string
        code:
          type: integer
        message:
          type: string
        total:
          type: integer
        pagination:
          type: object
          properties:
            limit:
              type: integer
            offset:
              type: integer
            page:
              type: integer
